services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: liberx
      POSTGRES_PASSWORD: liberxx
      POSTGRES_DB: prod_db
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dockerfile
    container_name: liber_x_backend
    volumes:
      - ./backend:/app
    command: npx nodemon --legacy-watch --watch .
    ports:
      - "5001:5000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://liberx:liberxx@postgres:5432/prod_db
      #DATABASE_URL: postgres://postgres:BWoUX81AOayLOG02khGGod8d7654gfrt586@staging-main.cd8sgc8cmt5o.eu-west-2.rds.amazonaws.com:5432/staging
      QUEUE_URL: redis://redis:6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: liber_x_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
